language: generic

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-7
            - cmake-data
            - cmake
            - lcov
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - git clone https://github.com/satya-das/cib.git
  - git clone https://github.com/satya-das/cppparser.git
  - git clone https://github.com/satya-das/common.git
  - mkdir -p build_results/GNU
  - cd build_results/GNU
  - cmake -DCMAKE_C_COMPILER=`which gcc-7` -DCMAKE_CXX_COMPILER=`which g++-7` ../../cib/
  - make
  - make CibCoverage

after_success:
  - cd ../..
  - bash <(curl -s https://codecov.io/bash) -f build_results/GNU/examples/cib.info -t"66bf246c-fcae-4dcc-8101-44e7e66e467d" || echo "Codecov did not collect coverage reports"


